services:
  - type: web
    name: lyzr-support-backend
    env: node
    buildCommand: ./render-build.sh
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
